### ISSUE TITLE
whenProxy

### ISSUE THREAD

**Issue by IdoJS** [scalecube/scalecube-js#133]
## General description

whenProxy will listen to the registry.
once the serviceDefinition is available in the registry then it will resolve with a proxy to the serviceDefinition

```
ms
  .whenProxy({serviceDefinition})
  .then(proxy => {
  // Use the service via proxy here
});
```

#### Prerequisites

Links to any external dependency for this feature

[Link]

#### Design proposition

A clear and concise description of the design proposition.

- [x] Is backward compatible

- [x] Adds new API

- [x] Changes existing API

#### Pull Request

[Link]

#### Old API

Code snippet

```typescript
/**
 * Provides the functionality of a microservice container
 */
export default interface Microservice {
  /**
   * The method is used to delete a microservice and close all the subscriptions related with it
   */
  destroy(): null;

  /**
   * Creates a proxy to a method and provides extra logic when is invoked
   */
  createProxy(proxyOptions: ProxyOptions, router ?: Router): {[proxyName: string]: any};

  /**
   * Exposes serviceCall to a user (not via Proxy)
   */
  createServiceCall(options: CreateServiceCallOptions): ServiceCall;
}
```

#### New API

Code snippet

```ts
/**
 * Provides the functionality of a microservice container
 */
export default interface Microservice {
  /**
   * The method is used to delete a microservice and close all the subscriptions related with it
   */
  destroy(): null;

  /**
   * Creates a proxy to a method and provides extra logic when is invoked
   */
  createProxy(proxyOptions: ProxyOptions, router ?: Router): {[proxyName: string]: any};

  /**
   * Exposes serviceCall to a user (not via Proxy)
   */
  createServiceCall(options: CreateServiceCallOptions): ServiceCall;

  /**
   * Resolve a proxy to the service only after the service is available in the registry
   */
  whenProxy<T = any>(wpOptions : WhenProxyOptions): Promise<T>;
}

interface WhenProxyOptions {
  /**
   * Contract of the service
   */
 serviceDefinition: ServiceDefinition;
  /**
   * Pluggable router implementation - optional
   */
 router ?: Router
}
```

#### Consideration

List of everything to consider before writing test cases:

- [ ] Changes current behaviour

Specify which behaviour will be changed and how or provide the link to PR.

- [ ] Is specific to some devices/browsers/environments

Specify which behaviour will be changed and how or provide the link to PR.

- [ ] Requires the usage of external npm modules

Provide the list of modules with a brief description why this module is required.

## Test cases

Link to the PR with test cases, that are written in _**Gherkin Syntax**_ and cover all the possible scenarios.

[Link]

## Key Performance Indicator (KPI) Definition

A clear target that can be measured by the change.

_**Example:** reduce bundle size by X%._

####

- [ ] External dependencies have been resolved

- [ ] API has been approved

- [ ] Test cases have been prepared

- [ ] Discussed with Technical lead

####

- [ ] Technical review

- [ ] All tests are implemented 

- [ ] Documentation

- [ ] Release notes

- [ ] KPI has been reached

## RoadMap

In case there is more than one mergable point you can specify it here.

NOTICE that DoD is one unit, you CAN'T do implementation then notes then documentation etc.

**Comment by IdoJS** [comment]
add this functionality to createProxy
https://github.com/scalecube/scalecube-js/issues/83
