### ISSUE TITLE
Tags weighting Router

### ISSUE THREAD

**Issue by katzIdo** [scalecube/scalecube-js#179]
## General description

Tags weighting - pick the next service base on the "weight" of the service

#### Prerequisites

Links to any external dependency for this feature

[Link]

#### Design proposition

A clear and concise description of the design proposition.

- [ ] Is backward compatible

- [ ] Adds new API

- [ ] Changes existing API

- [ ] Removes existing API

#### Pull Request

[Link]

#### Old API

Code snippet

```typescript
```

#### New API

Code snippet

```typescript
```

#### Consideration

List of everything to consider before writing test cases:

- [ ] Changes current behaviour

Specify which behaviour will be changed and how or provide the link to PR.

- [ ] Is specific to some devices/browsers/environments

Specify which behaviour will be changed and how or provide the link to PR.

- [ ] Requires the usage of external npm modules

Provide the list of modules with a brief description why this module is required.

## Test cases

Link to the PR with test cases, that are written in _**Gherkin Syntax**_ and cover all the possible scenarios.

[Link]

## Key Performance Indicator (KPI) Definition

A clear target that can be measured by the change.

_**Example:** reduce bundle size by X%._

####

- [ ] External dependencies have been resolved

- [ ] API has been approved

- [ ] Test cases have been prepared

- [ ] Discussed with Technical lead

####

- [ ] Developer review

- [ ] QA review

- [ ] All tests are implemented 

- [ ] Documentation

- [ ] KPI has been reached

## RoadMap

In case there is more than one mergable point you can specify it here.

NOTICE that DoD is one unit, you CAN'T do implementation then notes then documentation etc.
