### ISSUE TITLE
create release package for @scalecube/browser

### ISSUE THREAD

**Issue by katzIdo** [scalecube/scalecube-js#213]
## General description

create package with scalecube that contains all the plugins for running in the browser.

bundles:

- iife

- esm

- cjs

## Test cases

change examples for using scalecube at browser environment to run with scalecube-browser
 
####

- [ ] External dependencies have been resolved

- [ ] API has been approved

- [ ] Test cases have been prepared

- [ ] Discussed with Technical lead

####

- [ ] Developer review

- [ ] QA review

- [ ] All tests are implemented 

- [ ] Documentation

- [ ] KPI has been reached

## RoadMap

In case there is more than one mergable point you can specify it here.

NOTICE that DoD is one unit, you CAN'T do implementation then notes then documentation etc.
