### ISSUE TITLE
update microservice integration tests

### ISSUE THREAD

**Issue by IdoJS** [scalecube/scalecube-js#88]
## General description

Update integration tests to test only with API, using gherkin syntax.

#### Prerequisites

1. Tests are integrated into the code in spec.ts fils at
[tree/feature/tests-microservices](https://github.com/scalecube/scalecube-js/tree/feature/tests-microservices) (Branch).
2. Tests will be performed only by using the API and test the API.

#### Pull Request
[Success scenario ](https://github.com/scalecube/scalecube-js/pull/92 )
[microservice - definition validation](https://github.com/scalecube/scalecube-js/pull/116)
###### Test LocalCall - a microservice instance use its own services.
1. Creating a microservice with service & serviceDefinition.
2. Creating a proxy || serviceCall from the microservice instance.
3. Invoke || subscribe to a method successfully.
4. Receive response
          
###### Test RemoteCall - a microservice instance use other microservice's services.
1. Creating a microservice (remote) with service & serviceDefinition and with seedAddress='defaultSeedAddress'.
2. Creating a microservice (local) without services but with seedAddress='defaultSeedAddress'.
3. Discoveries discover other microservices under the same seed.
4. Creating a proxy || serviceCall from the local microservice instance.
5. Invoke || subscribe to a method successfully.
6. Receive response

##### Warnings
- [service got reference that are not in definition - console notification](https://github.com/scalecube/scalecube-js/issues/112)

##### Validation
1. Error messages after failed attempts to create a microservice
- [x] [microservice - serviceDefinition asyncModel value](https://github.com/scalecube/scalecube-js/issues/101)
- [x] [microservice - serviceDefinition method format](https://github.com/scalecube/scalecube-js/issues/100)
- [x] [seedAddress:string](https://github.com/scalecube/scalecube-js/issues/99)
- [x] [microservice - services : Service[]](https://github.com/scalecube/scalecube-js/issues/102)
- [x] [microservice - serviceDefinition without serviceName](https://github.com/scalecube/scalecube-js/issues/105)

2. Error messages after failed attempts to create a Proxy.
- [x]  [proxy - serviceDefinition asyncModel value](https://github.com/scalecube/scalecube-js/issues/103)
- [x]  [proxy - serviceDefinition method format](https://github.com/scalecube/scalecube-js/issues/104)
- [x]  [proxy - serviceDefinition without serviceName](https://github.com/scalecube/scalecube-js/issues/106)
- [x]  [asyncModel in Proxy doesn't match the microservice asyncModel (remote & local)](https://github.com/scalecube/scalecube-js/issues/107)

3. Error messages after failed attempts to create a serviceCall.
- [x]  [serviceCall without message](https://github.com/scalecube/scalecube-js/issues/109)
- [x]  [asyncModel in serviceCall doesn't match the microservice asyncModel (remote & local)](https://github.com/scalecube/scalecube-js/issues/108)
- [x]  [ serviceCall message data is not an array](https://github.com/scalecube/scalecube-js/issues/110)
- [x]  [ serviceCall qualifier is not type string](https://github.com/scalecube/scalecube-js/issues/111)

#### Successful validation
- [Successful validation when creating a microservice](https://github.com/scalecube/scalecube-js/issues/113).
- [Successful validation when creating a proxy](https://github.com/scalecube/scalecube-js/issues/114).
- [Successful validation when creating a serviceCall](https://github.com/scalecube/scalecube-js/issues/115)

## Definition of Done
- [x] Technical lead review
- [x] Team member (QA) review
- [x] All tests are implemented 
- [x] Documentation
